# Generated by Django 3.2.15 on 2024-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20240122_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='username',
            field=models.CharField(default='username', max_length=255),
        ),
    ]
