# Generated by Django 3.2.15 on 2024-01-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_postmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
