# Generated by Django 3.2.15 on 2024-01-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_postmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user',
        ),
    ]
