# Generated by Django 3.2.15 on 2024-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
