# Generated by Django 3.2.15 on 2024-01-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20240124_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='username',
        ),
    ]
