# Generated by Django 3.2.15 on 2024-01-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_postmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='username',
        ),
    ]
