# Generated by Django 3.2.15 on 2024-01-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_postmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
