# Generated by Django 3.2.15 on 2024-01-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_postmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='baggage_number',
            field=models.CharField(default=11111, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
